routes:
  

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: tag:-[links,newsletter]

  /links/:
    permalink: /links/{slug}/
    template: index
    filter: tag:[links]
    order: published_at desc

  /gtt/:
    permalink: /gtt/{slug}/
    template: index
    filter: tag:[newsletter]
    order: published_at desc

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
